### ISSUE TITLE
Frontend issues 

### ISSUE THREAD

**Issue by mablae** [xsolve-pl/boldare-tech#48]
The frontend won't render complete with adblock active.

**Comment by mateuszmatyszkowicz** [comment]
Hi @mablae sorry for my late response, Could you tell a little bit more about the issue. What are the steps to reproduce problem and what OS did you used? Btw, Thanks for your activity🥇

**Comment by Destroy666x** [comment]
@mablae we introduced some changes, do you still have any issues? If so, please let us know and share the console output.

**Comment by mablae** [comment]
Seems to be fine now 👍

**Comment by Destroy666x** [comment]
Thanks for info, closing then.
